import { useEffect, useState, useContext } from 'react';
import Head from 'next/head';
import { TodoList } from 'src/components/TodoList';
import { TodoContext } from 'src/contexts/TodoContext';
import { TodoCreateInput } from 'src/components/TodoCreateInput';

export default function Home() {
  const { todos, fetchAllTodos } = useContext(TodoContext);

  useEffect(() => {
    fetchAllTodos();
  }, [todos]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoCreateInput />
      <TodoList todos={todos} />
    </div>
  );
}
